{% set name = "csvtk" %}
{% set version = "0.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shenwei356/csvtk/archive/v{{ version }}.tar.gz
  sha256: 90068a24f055076d65f54b18fa796b5322ffe728687d972038bb2ffa2ca07be8

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - csvtk --help

about:
  home: https://github.com/shenwei356/csvtk
  license: MIT
  license_file:
    - LICENSE
    - csvtk/license-files/
  summary: A cross-platform, efficient and practical CSV/TSV toolkit in Golang

extra:
  recipe-maintainers:
    - shenwei356
    - apcamargo
